spring:
  application:
    name: projectos
  # --- H2 Database Configuration ---
  datasource:
    url: jdbc:h2:mem:testdb # In-memory database named 'testdb'
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true # This enables the /h2-console endpoint
